name: b3bp CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@master
        with:
          node-version: 18.x
      - name: Install
        run: |
          corepack yarn
      - name: Lint
        run: |
          corepack yarn lint
      - name: Test
        run: |
          corepack yarn test
      - name: Website Build
        if: github.ref == 'refs/heads/main'
        run: |
          cp README.md docs/
